name: Build

on: 
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Web
    strategy:
      matrix:
        node-version: [18.x]
    if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.action == 'assigned'

    steps:    
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build using Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: npm ci
    - name: Build project
      run: npm run build
    - name: Cache artifacts
      uses: actions/cache@v1
      id: cache-build
      with:
        path: '.'
        key: ${{ github.sha }}

  lint:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Restore cached artifacts
      uses: actions/cache@v1
      id: restore-build
      with:
        path: '.'
        key: ${{ github.sha }}
    - name: Eslint
      run: npm run lint
