name: Build, Danger

on: 
  pull_request:
    branches:
    - main
  push:
    branches:
      - main
    
permissions:
  actions: write
  checks: write
  contents: write
  issues: write
  pull-requests: write
  statuses: write

jobs:
  danger:
    if: ${{ github.event_name == 'pull_request' }}
    name: Danger JS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Danger
        uses: danger/danger-js@9.1.6
        with:
          args: "--dangerfile ./.github/workflows/dangerfile.js"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DANGER_DISABLE_TRANSPILATION: true
        
  build:
    runs-on: ubuntu-latest
    needs: danger
    defaults:
      run:
        working-directory: ./Web
    strategy:
      matrix:
        node-version: [18.x]
    if: ${{ github.actor == 'Hikoya' && github.event.action == 'opened' }}

    steps:    
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build using Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: npm ci
    - name: Build project
      run: npm run build
    - name: Cache artifacts
      uses: actions/cache@v1
      id: cache-build
      with:
        path: '.'
        key: ${{ github.sha }}

  lint:
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        working-directory: ./Web
    if: ${{ github.actor == 'Hikoya' && github.event.action == 'opened' }}

    steps:
    - name: Restore cached artifacts
      uses: actions/cache@v1
      id: restore-build
      with:
        path: '.'
        key: ${{ github.sha }}
    - name: Eslint
      run: npm run lint

  heroku:
    runs-on: ubuntu-latest
    if: ${{ github.event.action == 'closed' && github.event.pull_request.merged == true  }}
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "orbital-armazing"
          heroku_email: "hikoyanamikaze@gmail.com"
          appdir: "Web"
